# Generated by Django 5.1.7 on 2025-03-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('tip', models.CharField(choices=[('tek', 'Tek Bitki'), ('karisim', 'Karışım')], default='tek', max_length=10)),
                ('resim', models.ImageField(blank=True, null=True, upload_to='bitkiler/')),
                ('faydalar', models.TextField()),
                ('kullanim', models.TextField()),
                ('hazirlama', models.TextField()),
                ('uyarilar', models.TextField(blank=True)),
                ('doz', models.CharField(max_length=200)),
                ('rahatsizliklar', models.TextField()),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bitki',
                'verbose_name_plural': 'Bitkiler',
                'ordering': ['isim'],
            },
        ),
    ]
