# Generated by Django 5.1.7 on 2025-03-22 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifalibitkiler', '0002_rahatsizlik_alter_bitki_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rahatsizlik',
            options={'ordering': ['isim'], 'verbose_name': 'Rahatsızlık', 'verbose_name_plural': 'Rahatsızlıklar'},
        ),
        migrations.AddField(
            model_name='rahatsizlik',
            name='belirtiler',
            field=models.TextField(blank=True, help_text='Rahatsızlığın belirtilerini yazın'),
        ),
        migrations.AddField(
            model_name='rahatsizlik',
            name='onlemler',
            field=models.TextField(blank=True, help_text='Alınması gereken önlemleri yazın'),
        ),
        migrations.AddField(
            model_name='rahatsizlik',
            name='risk_faktorleri',
            field=models.TextField(blank=True, help_text='Risk faktörlerini yazın'),
        ),
        migrations.AlterField(
            model_name='rahatsizlik',
            name='isim',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='rahatsizlik',
            name='olusturulma_tarihi',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
