# Generated by Django 4.1.13 on 2025-04-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifalibitkiler', '0004_karisim_alter_bitki_options_bitki_aile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitki',
            name='kullanim_alani',
            field=models.TextField(blank=True),
        ),
    ]
