# Generated by Django 4.2.7 on 2025-04-08 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sifalibitkiler', '0005_bitki_kullanim_alani'),
    ]

    operations = [
        migrations.CreateModel(
            name='KullaniciAramaGecmisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arama_tarihi', models.DateTimeField(auto_now_add=True)),
                ('konum', models.CharField(blank=True, max_length=100, null=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arama_gecmisi', to=settings.AUTH_USER_MODEL)),
                ('rahatsizlik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sifalibitkiler.rahatsizlik')),
            ],
            options={
                'verbose_name': 'Kullanıcı Arama Geçmişi',
                'verbose_name_plural': 'Kullanıcı Arama Geçmişleri',
                'ordering': ['-arama_tarihi'],
            },
        ),
    ]
