# Generated by Django 4.1.13 on 2025-05-05 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sifalibitkiler', '0003_alter_rahatsizlik_options_rahatsizlik_belirtiler_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitki',
            options={'ordering': ['isim'], 'verbose_name': 'Bitki', 'verbose_name_plural': 'Bitkiler'},
        ),
        migrations.AddField(
            model_name='bitki',
            name='aile',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bitki',
            name='bilimsel_ad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bitki',
            name='cins',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bitki',
            name='etiketler',
            field=models.TextField(blank=True, help_text='Etiketleri virgülle ayırarak yazın'),
        ),
        migrations.AddField(
            model_name='bitki',
            name='kaynak',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bitki',
            name='kontrendikasyonlar',
            field=models.TextField(blank=True, help_text='Kontrendikasyonları virgülle ayırarak yazın'),
        ),
        migrations.AddField(
            model_name='bitki',
            name='mevsim',
            field=models.TextField(blank=True, help_text='Mevsimleri virgülle ayırarak yazın'),
        ),
        migrations.AddField(
            model_name='bitki',
            name='raf_omru',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bitki',
            name='saklama_kosullari',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bitki',
            name='tur',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bitki',
            name='yan_etkiler',
            field=models.TextField(blank=True, help_text='Yan etkileri virgülle ayırarak yazın'),
        ),
        migrations.AddField(
            model_name='rahatsizlik',
            name='etiketler',
            field=models.TextField(blank=True, help_text='Etiketleri virgülle ayırarak yazın'),
        ),
        migrations.AddField(
            model_name='rahatsizlik',
            name='seviye',
            field=models.CharField(choices=[('hafif', 'Hafif'), ('orta', 'Orta'), ('ciddi', 'Ciddi'), ('acil', 'Acil')], default='orta', max_length=20),
        ),
        migrations.AddField(
            model_name='rahatsizlik',
            name='yayginlik',
            field=models.CharField(choices=[('nadir', 'Nadir'), ('az', 'Az'), ('orta', 'Orta'), ('yaygin', 'Yaygın'), ('cok_yaygin', 'Çok Yaygın')], default='orta', max_length=20),
        ),
        migrations.AlterField(
            model_name='bitki',
            name='doz',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bitki',
            name='olusturulma_tarihi',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bitki',
            name='tip',
            field=models.CharField(choices=[('ot', 'Ot'), ('agac', 'Ağaç'), ('cicek', 'Çiçek'), ('meyve', 'Meyve'), ('kök', 'Kök'), ('tohum', 'Tohum'), ('yaprak', 'Yaprak'), ('diger', 'Diğer')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='bitki',
            index=models.Index(fields=['isim'], name='sifalibitki_isim_a9c8bf_idx'),
        ),
        migrations.AddIndex(
            model_name='bitki',
            index=models.Index(fields=['tip'], name='sifalibitki_tip_3f902a_idx'),
        ),
        migrations.AddIndex(
            model_name='bitki',
            index=models.Index(fields=['bilimsel_ad'], name='sifalibitki_bilimse_b1b64b_idx'),
        ),
        migrations.AddIndex(
            model_name='rahatsizlik',
            index=models.Index(fields=['isim'], name='sifalibitki_isim_2edf65_idx'),
        ),
        migrations.AddIndex(
            model_name='rahatsizlik',
            index=models.Index(fields=['seviye'], name='sifalibitki_seviye_af7c7f_idx'),
        ),
    ]
